# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

# Pipeline that publishes AML Pipeline for model training

trigger:
- none

schedules:
- cron: "0 14 1 * *"
  displayName: Monthly Retrain
  branches:
    include:
    - master
  always: true

variables:
- template: ../configuration/configuration-aml.variables.yml
- template: ../configuration/configuration-infra-DEV.variables.yml

pool:
  vmImage: ubuntu-latest

stages:

############################
##      Build Docker      ##
############################

- stage: Build_Training_Image
  jobs:
  - template: templates/docker-build.template.yml
    parameters:
      dockerfile: docker/tf_1/Dockerfile
      repository: tensorflowobjectdetection
      acrServiceConnection:  $(SERVICECONNECTION_CR)
      buildContext: $(Build.Repository.LocalPath)
      tags: latest

####################
##  RUN TRAINING  ##
####################

- stage: training
  displayName: 'Model Training/Retraining'
  dependsOn: Build_Training_Image
  jobs:
  - job: training_build
    displayName: 'Publish Training AML Pipeline'
    steps:
    - template: templates/utils/run-aml-python-code.template.yml
      parameters:
        serviceConnection: $(SERVICECONNECTION_WS)
        resourceGroup: $(RESOURCE_GROUP)
        amlWorkspace: $(AMLWORKSPACE)
        scriptPath: operation/execution/build_training_pipeline.py
        scriptExtraDependencies: pyyaml
        scriptArguments: --version  $(Build.BuildId)

  - template: templates/utils/invoke-aml-pipeline.template.yml
    parameters:
      dependsOn: training_build
      jobDisplayName: 'Invoke Training AML Pipeline'
      serviceConnection: $(SERVICECONNECTION_WS)
      resourceGroup: $(RESOURCE_GROUP)
      amlWorkspace: $(AMLWORKSPACE)
      pipelineName: $(AML_TRAINING_PIPELINE)
      experimentName: $(AML_TRAINING_EXPERIMENT)


#####################
##  APPROVE/REJECT ##
#####################

- stage: manual_validation
  displayName: 'Manual validation of AML training results'
  condition: and(succeeded('training'), eq(variables.RELEASE_TYPE, 'manual'))
  dependsOn: training
  jobs:
  - template: templates/manual-validation.template.yml
    parameters:
      businessOwnerEmail: $(BUSINESS_OWNER_EMAIL)
      instructionsText: 'Please approve or reject latest detection model'

#########################################
##  DEPLOY IN ACI (dev/test purposes)  ##
#########################################

- stage: deploy_model_aci
  displayName: 'Deploy Model to ACI'
  dependsOn: manual_validation
  jobs:
  - template: templates/deploy-model.template.yml
    parameters:
      environment: $(ENVIRONMENT)
      serviceConnection: $(SERVICECONNECTION_WS)
      resourceGroup: $(RESOURCE_GROUP)
      amlWorkspace: $(AMLWORKSPACE)
      deploymentType: aci
      webserviceName: $(AML_WEBSERVICE)-aci
      deleteAfterwards: true


#####################
##  DEPLOY IN AKS  ##
#####################

- stage: deploy_model_aks
  displayName: 'Deploy Model to AKS'
  dependsOn: deploy_model_aci
  jobs:
  - template: templates/deploy-model.template.yml
    parameters:
      environment: $(ENVIRONMENT)
      serviceConnection: $(SERVICECONNECTION_WS)
      resourceGroup: $(RESOURCE_GROUP)
      amlWorkspace: $(AMLWORKSPACE)
      deploymentType: aks
      webserviceName: $(AML_WEBSERVICE)
